In [1]:
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import os.path
from os import path

C:\Users\nikce\anaconda3\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\nikce\anaconda3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [2]:
def pngToTensor(image):
    img = Image.open(image)
    convert_tensor = transforms.ToTensor()
    img = convert_tensor(img)
    return img

In [3]:
def PCA(A, k):
        [u, s, v] = torch.pca_lowrank(A, q = k, center = False, niter = 10)
        Approx = u @ torch.diag(s) @ v.T
        return Approx

In [6]:
x = 1
inputVars = torch.zeros(1043, 200, 407)
outputVars = torch.zeros(1043, 7)

while x <= 1043:
    y = x - 1
    preString = str(x)
    if len(preString) == 1:
        myString ="000" + preString
    if len(preString) == 2:
        myString ="00" + preString
    if len(preString) == 3:
        myString = "0" + preString
    A = "C:/Users/nikce/anaconda3/Project/images/"
    
    if path.exists(A + myString + "_1" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_1" + ".png")
        outputVars[y][0] = 1
        
    elif path.exists(A + myString + "_2" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_2" + ".png")
        outputVars[y][1] = 1
        
    elif path.exists(A + myString + "_3" + ".png"):    
        inputVars[y] = pngToTensor(A + myString + "_3" + ".png")
        outputVars[y][2] = 1
        
    elif path.exists(A + myString + "_4" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_4" + ".png")
        outputVars[y][3] = 1
         
    elif path.exists(A + myString + "_5" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_5" + ".png")
        outputVars[y][4] = 1
        
    elif path.exists(A + myString + "_6" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_6" + ".png")
        outputVars[y][5] = 1
        
    elif path.exists(A + myString + "_7" + ".png"):
        inputVars[y] = pngToTensor(A + myString + "_7" + ".png")
        outputVars[y][6] = 1
        
    x = x + 1

In [43]:
k = 10 #input rank to test
A1 = PCA(inputVars[218], k)
A2 = PCA(inputVars[0], k)
A3 = PCA(inputVars[27], k)
A4 = PCA(inputVars[37], k)
A5 = PCA(inputVars[81], k)
A6 = PCA(inputVars[121], k)
A7 = PCA(inputVars[151], k)

In [53]:
count = 0
test = torch.zeros(7)

for i in range(1043):

    inputVal = inputVars[i]


    test[0] = torch.norm(inputVal - A1, p='fro')
    test[1] = torch.norm(inputVal - A2, p='fro')
    test[2] = torch.norm(inputVal - A3, p='fro')
    test[3] = torch.norm(inputVal - A4, p='fro')
    test[4] = torch.norm(inputVal - A5, p='fro')
    test[5] = torch.norm(inputVal - A6, p='fro')
    test[6] = torch.norm(inputVal - A7, p='fro')
    
    value, pred = torch.min(test, 0)
    ovalue, opred = torch.min(outputVars[i], 0)
    
    print(i)
    print(test)

    
    if pred == opred:
        count = count + 1



0
tensor([108.0290,  27.7186,  83.2674,  94.0097,  82.6525, 102.1317,  84.3752])
1
tensor([97.5195, 81.5119, 76.1477, 99.2483, 76.3731, 98.5365, 70.5795])
2
tensor([107.1498,  69.5844,  81.9026,  98.3512,  76.7214, 100.1418,  79.0343])
3
tensor([103.3775,  79.0929,  88.7987,  87.6917,  75.3311,  93.7864,  78.6842])
4
tensor([108.4885,  86.9119,  90.7512,  94.1412,  80.3250,  86.2752,  86.0338])
5
tensor([ 98.8148,  77.8819,  78.3001, 103.6004,  80.4019, 104.4853,  79.6341])
6
tensor([98.0783, 81.7772, 89.1451, 88.7527, 77.6188, 93.9319, 80.1312])
7
tensor([102.0918,  74.6905,  93.3404,  84.9578,  78.5518,  90.3092,  84.0551])
8
tensor([109.0857,  78.1838,  98.0554,  82.9779,  78.6242,  85.2604,  87.0118])
9
tensor([108.9900,  85.9860,  88.9189,  94.8691,  78.6271,  89.7849,  88.9205])
10
tensor([ 98.2304,  71.3575,  66.7455,  97.1440,  73.4530, 102.8109,  65.8098])
11
tensor([103.2961,  80.4677,  79.2804,  91.6775,  74.6257,  93.5747,  75.8089])
12
tensor([106.3632,  82.8623,  79.9730,

119
tensor([113.2951,  94.8647, 105.3354,  89.3308,  80.9605,  80.5596,  92.5121])
120
tensor([106.5666, 101.0353,  91.2180, 102.4872,  86.6099,  94.9257,  96.8870])
121
tensor([117.4218, 101.5422, 116.3992,  88.5791,  94.9727,  26.0586, 102.2109])
122
tensor([110.3184, 101.2378, 100.2277,  99.9700,  86.0773,  81.1103,  91.9522])
123
tensor([113.4374, 100.2885,  99.2820,  94.1227,  91.9763,  99.3767,  97.1499])
124
tensor([119.1504,  95.8830,  97.1072,  85.9285,  83.3580,  94.6054,  92.8551])
125
tensor([125.5065,  99.7984, 103.6490, 105.3430,  98.3730, 102.2643, 103.0921])
126
tensor([117.3524,  99.8077,  95.9641,  91.3130,  81.2084, 102.2248,  95.0525])
127
tensor([108.7529, 105.3641,  95.1496, 106.1106,  91.0831, 107.1783,  94.6813])
128
tensor([120.8926, 114.7290, 112.1690, 107.8752, 106.3874,  99.6660, 112.5238])
129
tensor([101.9705, 101.4007, 106.7924,  87.3772,  86.6351,  79.7112,  92.6224])
130
tensor([119.0373,  89.5856, 106.1028,  84.4981,  88.3102,  77.0705,  94.2386])
131


241
tensor([ 78.6789, 105.0178, 105.7035, 114.5570, 103.4353, 110.2255, 101.7494])
242
tensor([ 87.7332, 100.1180, 106.1247, 119.5015, 101.7480, 115.1865,  99.0036])
243
tensor([ 89.8778, 105.0848, 106.0967, 124.8339, 111.0547, 125.7170, 113.3285])
244
tensor([ 79.7290, 103.1093,  96.3355, 119.2851, 103.6267, 123.1260, 100.8286])
245
tensor([110.7335, 109.9863, 112.1130, 109.6790, 102.2874,  95.6274, 107.6320])
246
tensor([ 93.6656,  96.4954,  96.0172, 109.7663,  97.5924, 110.3328,  92.3686])
247
tensor([ 96.0847, 106.6758, 105.1741, 120.7830, 110.5424, 124.8920, 112.0235])
248
tensor([100.5262,  98.2041,  92.7828, 110.5695,  94.6750, 119.5862, 100.5796])
249
tensor([ 97.3003,  99.2228,  97.5444, 109.2518,  94.0712, 118.4988, 101.3002])
250
tensor([ 96.7895, 101.3833, 109.1746, 112.2211, 104.1508, 102.8665, 104.5884])
251
tensor([ 90.8434, 101.1855,  99.6616, 112.4720, 100.9638, 113.5292, 100.9421])
252
tensor([ 90.6871, 100.4222, 103.3244, 117.7698, 109.9113, 117.2149, 107.1656])
253


349
tensor([ 92.0897,  88.7358,  97.9180, 106.1388,  98.7499, 108.1945,  97.0485])
350
tensor([ 92.1140, 108.7396, 107.2468, 113.8984, 104.4171, 108.2575, 106.4973])
351
tensor([ 99.7194,  95.8551, 103.5728, 106.0648, 101.3280, 118.2575, 102.8261])
352
tensor([105.5962, 105.8688, 112.1745, 102.5120, 102.4573, 111.4883, 106.9428])
353
tensor([ 89.6892, 102.0606, 108.5714, 112.8505, 102.4347, 113.3862,  99.0028])
354
tensor([ 99.6107,  83.8577,  87.5431, 101.1247,  88.9231, 112.2270,  97.6786])
355
tensor([107.0093,  97.7048,  95.4230, 104.4826,  93.8858, 114.4631,  99.3814])
356
tensor([108.9526, 101.1724, 102.7424, 106.1597, 102.1276, 117.4707, 103.5893])
357
tensor([ 98.9094, 106.0270, 100.7687, 111.8317, 104.0496, 112.2354, 100.5791])
358
tensor([ 94.1984,  94.4493, 106.0455, 112.3114, 101.4352, 108.1303,  98.4684])
359
tensor([ 90.2409, 101.5045, 105.3262, 113.6172, 109.9268, 116.5612, 107.5191])
360
tensor([103.8938,  87.3065,  94.7651, 100.2270,  92.6026, 116.9211,  99.9253])
361


tensor([ 74.6247, 103.9152,  91.6238, 116.6442, 100.6218, 119.6586,  93.6714])
461
tensor([ 83.4048,  96.0181,  88.3991, 123.2818,  98.4561, 116.7440,  91.7914])
462
tensor([ 85.5909, 106.2679, 103.5451, 117.0725, 106.5633, 116.1668, 111.2088])
463
tensor([ 94.5300,  99.1556, 105.7426, 110.2438, 104.3444, 114.0427, 101.1743])
464
tensor([ 83.5361, 113.8811, 117.5355, 118.8748, 111.3430, 116.1872, 110.7844])
465
tensor([ 86.8304,  94.5983,  90.3190, 114.7288,  93.3821, 110.0816,  90.6412])
466
tensor([ 93.2118,  97.5891, 101.6932, 114.8642, 102.6377, 115.2030, 101.3106])
467
tensor([ 91.4504, 100.4139,  82.0501, 110.3183,  83.5189, 111.7550,  88.1663])
468
tensor([ 94.5574, 104.6719, 103.5728, 112.3025, 100.7482, 114.3906, 102.5235])
469
tensor([ 94.4002, 101.9298, 112.4279, 112.2945, 108.7043, 108.8409, 103.3740])
470
tensor([ 83.5064,  97.5306, 102.8628, 112.3273, 100.3462, 106.7969,  94.7528])
471
tensor([ 99.9026, 100.0103, 110.6274, 111.3169, 105.8644, 119.7952, 105.8827])
472
tens

tensor([ 84.8236,  93.8477,  89.8226, 114.2549,  99.9854, 122.9663,  99.6648])
582
tensor([ 98.5654,  93.3137,  91.2262, 104.4524,  88.0016,  99.4192,  93.8604])
583
tensor([ 92.0734, 105.5023,  91.2499, 116.9437, 102.2636, 128.8847, 105.0740])
584
tensor([ 92.4709,  95.3793,  82.8482, 106.1909,  89.1717, 118.6192,  92.8061])
585
tensor([ 98.5585, 117.5914, 105.7355, 115.1709,  97.3874, 103.2606, 106.1090])
586
tensor([ 97.6608, 109.0113, 102.0930, 112.7723,  95.0101, 103.3579,  98.7978])
587
tensor([ 94.5377, 109.3546, 106.7085, 115.3907, 109.3953, 120.9944, 108.3000])
588
tensor([104.4927,  92.3997,  91.4369, 105.1832,  96.2267, 120.1860, 102.8757])
589
tensor([ 92.7789, 101.1938,  91.8677, 109.8588, 100.3452, 120.7898,  99.2657])
590
tensor([ 91.4738,  95.8383, 105.2678, 109.8323, 105.7390, 114.4965, 107.9801])
591
tensor([ 99.7402, 104.3686, 100.0497, 117.6572, 110.4946, 126.9034, 109.6929])
592
tensor([101.3432,  98.9401,  98.3019, 104.9169,  97.0761, 117.6626, 105.1740])
593
tens

tensor([ 96.8232, 106.9517,  97.2917, 120.0032, 101.1945, 107.8729, 104.5084])
701
tensor([101.6236, 102.2902, 101.0514, 109.1454, 101.9705, 128.1332, 108.7490])
702
tensor([102.6216,  85.3276,  80.9706, 107.7330,  91.6820, 119.0344,  93.9240])
703
tensor([100.5013,  88.6242,  86.8377, 107.2157,  91.7208, 113.4323,  95.2105])
704
tensor([107.8601,  99.7224, 106.1172, 106.6597, 101.0379, 122.3969, 108.3115])
705
tensor([108.2689,  84.8557,  92.4022, 100.4977,  97.8392, 116.9740,  98.9685])
706
tensor([ 97.0300,  95.1081,  85.6571, 104.6935,  87.8712, 114.4254,  92.5802])
707
tensor([ 98.7463, 100.3104,  88.9044, 111.2645,  93.0451, 119.0090, 102.7278])
708
tensor([ 93.0751,  95.9055,  98.0144, 111.6786, 105.6480, 119.8514, 105.3143])
709
tensor([ 90.4310,  93.4387,  96.4008, 112.1427, 102.2047, 121.6988,  98.2869])
710
tensor([ 84.1237,  99.2459,  88.8679, 123.3277, 104.9278, 129.1269, 100.8001])
711
tensor([100.9759,  97.1880,  96.8410, 122.0311, 108.0394, 131.3665, 109.3600])
712
tens

tensor([ 85.9508, 110.2405,  89.2961, 122.0569,  99.3739, 128.4168, 102.9070])
815
tensor([ 92.9776,  90.7441,  70.2297, 114.0133,  91.9328, 121.2512,  87.1016])
816
tensor([ 97.5617,  95.0381,  82.9280, 116.8605,  98.3198, 125.8776, 101.4886])
817
tensor([ 90.6218, 101.0255,  93.4259, 120.6006, 106.4667, 132.2215, 106.4037])
818
tensor([ 85.7814, 101.6487,  85.0724, 118.7073, 103.4870, 127.5785,  99.0884])
819
tensor([ 91.6231, 104.8952,  85.5779, 115.0524,  98.0478, 126.2687, 102.2124])
820
tensor([ 93.1740, 106.5796,  90.2174, 119.3729,  98.4956, 120.8759, 106.0765])
821
tensor([ 89.0894, 103.0078,  90.3506, 118.7623, 101.7345, 128.5246, 105.3497])
822
tensor([ 90.2440, 103.4334,  83.2160, 118.5205,  95.5637, 120.9611, 100.5701])
823
tensor([ 84.4384,  97.2595,  76.1556, 121.6486,  93.9239, 120.5333,  90.6995])
824
tensor([ 92.5332,  93.1578,  91.9912, 122.8806, 105.7427, 130.7106, 107.0786])
825
tensor([ 89.3590, 105.7747,  86.3086, 120.9902,  99.4024, 123.9920, 104.9604])
826
tens

tensor([ 96.0861, 102.3486,  88.7929, 118.5944, 101.2872, 126.4687, 101.2029])
936
tensor([ 96.0169, 105.2453,  93.3659, 113.4540, 102.1713, 129.2252, 106.6395])
937
tensor([ 92.2687, 106.3457, 102.0095, 115.8553, 108.5507, 130.2259, 111.5309])
938
tensor([ 91.1618,  98.0275,  79.0113, 122.2070,  98.6164, 124.6884,  96.9503])
939
tensor([ 91.4741,  96.7922,  82.8440, 115.9142,  95.4817, 121.4667,  97.1081])
940
tensor([ 84.9030, 106.4426,  84.0984, 126.1248, 100.3757, 127.1223, 100.9040])
941
tensor([ 97.3050, 110.2133,  97.6711, 120.4677, 107.9529, 128.6999, 110.6757])
942
tensor([ 87.7957,  99.4172,  83.3934, 124.4360, 100.5495, 128.0869, 102.2965])
943
tensor([ 86.5312, 106.9107,  90.9942, 121.8245,  98.6756, 120.6948, 102.4698])
944
tensor([ 87.6665, 105.1588,  80.8804, 121.0995,  97.9252, 126.0561,  99.2193])
945
tensor([ 89.1253,  99.6487,  89.1551, 119.1869,  99.2877, 125.2509, 100.5195])
946
tensor([ 89.2999, 107.2574,  90.3207, 123.0272, 102.7820, 130.9908, 106.4225])
947
tens

tensor([ 93.8112,  96.0983,  81.9373, 110.4067,  91.2756, 122.4014, 100.0740])
1042
tensor([ 93.8112,  96.0983,  81.9373, 110.4067,  91.2756, 122.4014, 100.0740])


In [54]:
print(count)

213
